name: Test Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
      
    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.9'

    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y xorg-dev libglu1-mesa-dev xpra xserver-xorg-video-dummy freeglut3-dev
    
    - name: install python packages
      run: python3 -m pip install numpy

    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DPYTHON_EXECUTABLE=$(python3 -c "import sys; print(sys.executable)") -DPOLYSCOPE_BACKEND_OPENGL3_EGL=ON ..

    - name: build
      run: cd build && cmake --build "." --parallel

    - name: run test backend mock
      run: python3 test/polyscope_test.py -v
    
    - name: run test backend EGL
      run: python3 test/polyscope_test.py -v backend=openGL3_egl